CREATE TABLE IF NOT EXISTS users (
  id       SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email    VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  tag      VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS deeds (
  id      SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title   VARCHAR(255) NOT NULL,
  done    BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS friends (
  id        SERIAL PRIMARY KEY,
  user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  friend_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE(user_id, friend_id)
);
